'use strict';

function clicksOven()
{
	var patch3c = "";
	var number = "";
	number = "logs";
	number = "logs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")' class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + number.toUpperCase());
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "oakLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")' class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "OAK");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "willowLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")'  class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "WILLOW");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "bambooLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")'  class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "BAMBOO");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "mapleLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")'  class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "MAPLE");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "lavaLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")'  class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "LAVA");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	number = "stardustLogs";
	patch3c = patch3c + ("<div onclick='addLogsOven(\"" + number + "\");closeDialogue(\"dialogue-confirm\")'  class='oven-log-button'>");
	patch3c = patch3c + "<table width='100%'>";
	patch3c = patch3c + "<tr>";
	patch3c = patch3c + "<td>";
	patch3c = patch3c + ("<img src='images/" + number + ".png' class='img-70' />");
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "<td style='text-align:right;'>";
	patch3c = patch3c + ("<span style='color:orange'>" + formatNumber(getItem(number)) + "</span><br /> " + "STARDUST");
	patch3c = patch3c + "<br /><br />";
	patch3c = patch3c + ("<img src='images/heat.png' class='img-20' /> " + getHeat(number));
	patch3c = patch3c + "</td>";
	patch3c = patch3c + "</table>";
	patch3c = patch3c + "</div>";
	confirmDialogue("none", patch3c, "Close", "", "");
};
