'use strict';

function hideAllRightTabs()
{
	document.getElementById("navigation-right-combat-select").style.display = "none";
	document.getElementById("navigation-right-combat-fighting").style.display = "none";
	document.getElementById("navigation-right-combat").style.display = "none";
	document.getElementById("navigation-right-shop").style.display = "none";
	document.getElementById("navigation-right-donorshop").style.display = "none";
	document.getElementById("navigation-right-shopOptions").style.display = "none";
	document.getElementById("navigation-right-quests").style.display = "none";
	document.getElementById("navigation-right-mining").style.display = "none";
	document.getElementById("navigation-right-magic").style.display = "none";
	document.getElementById("navigation-right-market").style.display = "none";
	document.getElementById("navigation-right-crafting").style.display = "none";
	document.getElementById("navigation-right-woodcutting").style.display = "none";
	document.getElementById("navigation-right-farming").style.display = "none";
	document.getElementById("navigation-right-brewing").style.display = "none";
	document.getElementById("navigation-right-treeList").style.display = "none";
	document.getElementById("navigation-right-cooksBook").style.display = "none";
	document.getElementById("navigation-right-manaStars").style.display = "none";
	document.getElementById("navigation-right-seedList").style.display = "none";
	document.getElementById("navigation-right-gemList").style.display = "none";
	document.getElementById("navigation-right-convertMagic").style.display = "none";
	document.getElementById("navigation-right-transformLog").style.display = "none";
	document.getElementById("navigation-right-museum").style.display = "none";
	document.getElementById("navigation-right-puzzleChest1").style.display = "none";
	document.getElementById("navigation-right-combatLog").style.display = "none";
	document.getElementById("navigation-right-skills").style.display = "none";
	document.getElementById("navigation-right-muteList").style.display = "none";
	document.getElementById("navigation-right-home").style.display = "none";
	document.getElementById("navigation-right-fishing").style.display = "none";
	document.getElementById("navigation-right-cooking").style.display = "none";
	document.getElementById("navigation-right-researcher").style.display = "none";
	document.getElementById("navigation-right-combat-button").style.color = "white";
	document.getElementById("navigation-right-shop-button").style.color = "white";
	document.getElementById("navigation-right-quests-button").style.color = "white";
	document.getElementById("navigation-right-mining-button").style.color = "white";
	document.getElementById("navigation-right-magic-button").style.color = "white";
	document.getElementById("navigation-right-crafting-button").style.color = "white";
	document.getElementById("navigation-right-woodcutting-button").style.color = "white";
	document.getElementById("navigation-right-farming-button").style.color = "white";
	document.getElementById("navigation-right-brewing-button").style.color = "white";
	document.getElementById("navigation-right-skills-button").style.color = "white";
	document.getElementById("navigation-right-home-button").style.color = "white";
};
