/**
 * loadItemBoxes extracted from ../../deobfuscated/bundle.js at line 5121-5620
 *
 * If this file doesn't contain a function, there is an error in ../raw/loadItemBoxes.js
 * You can fix it manually and use http://jsnice.org/ to make it nice
 **/

function loadItemBoxes()
{
	var _0x5B4C = "#262626";
	var _0x5BFA = "#665200";
	var _0x5BDD = "grey";
	var _0x5C17 = "#995c00";
	var _0x5C34 = "#331a00";
	var _0x5BC0 = "#003366";
	var _0x5BA3 = "#000d1a";
	var _0x5B69 = "#008000";
	var _0x5B86 = "#006600";
	if (getItemString("home") == "none")
	{
		addItemBox("donorCoins", 0, "", "item-section-combat-1", "green", "lime", "DONOR COINS", "tooltip-donorCoins", false)
	};
	addItemBox("lootBagLog", 0, "", "explorer-section", _0x5B4C, "grey", "LOOT BAG LOGS", "", false);
	addItemBox("fieldsLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "FIELDS", "tooltip-lootBag", false);
	addItemBox("forestLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "FOREST", "tooltip-lootBag", false);
	addItemBox("cavesLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "CAVES", "tooltip-lootBag", false);
	addItemBox("lavaDungeonLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "LAVA DUNG.", "tooltip-lootBag", false);
	addItemBox("northernFieldsLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "NORTH FIELDS", "tooltip-lootBag", false);
	addItemBox("cemeteryLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "CEMETERY", "tooltip-lootBag", false);
	addItemBox("oceanLootBag", 0, "", "explorer-section", _0x5BFA, _0x5BDD, "OCEAN", "tooltip-lootBag", false);
	addItemBox("readMe", 0, "", "item-section-combat-1", _0x5B4C, "grey", "READ ME", "", false);
	addItemBox("fightMonsterButton", 0, "", "item-section-combat-1", _0x5B4C, "grey", "FIGHT NPC", "", true);
	addItemBox("fightPvpButton", 0, "", "item-section-combat-1", _0x5B4C, "grey", "PVP", "", true);
	addItemBox("combatLog", 1, "", "item-section-combat-1", _0x5B4C, "grey", "MONSTER LOG", "tooltip-combatLog", false);
	addItemBox("combatPresetsIcon", 1, "", "item-section-combat-1", _0x5B4C, "grey", "PRESETS", "tooltip-combatPresetsIcon", false);
	addItemBox("explorer", 1, "", "item-section-combat-1", _0x5B4C, "grey", "EXPLORER", "tooltip-explorer", false);
	addItemBox("heartCrystal1", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "HEART CRYSTAL", "tooltip-heartCrystal", false);
	addItemBox("heartCrystal2", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "HEART CRYSTAL", "tooltip-heartCrystal", false);
	addItemBox("bones", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "BONES", "tooltip-bones", false);
	addItemBox("ashes", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ASHES", "tooltip-ashes", false);
	addItemBox("iceBones", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ICE BONES", "tooltip-iceBones", false);
	addItemBox("snakeBones", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "SNAKE BONES", "tooltip-snakeBones", false);
	addItemBox("skeletonSkull", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "SKULL", "tooltip-skeletonSkull", false);
	addItemBox("ghostClothes", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "GHOST CLOTHES", "tooltip-ghostClothes", false);
	addItemBox("snakeskin", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "SNAKESKIN", "tooltip-snakeskin", false);
	addItemBox("batSkin", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "BATSKIN", "tooltip-batSkin", false);
	addItemBox("bearFur", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "BEAR FUR", "tooltip-bearFur", false);
	addItemBox("polarBearFur", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "POLAR BEAR FUR", "tooltip-polarBearFur", false);
	addItemBox("blackSilk", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "BLACK SILK", "tooltip-blackSilk", false);
	addItemBox("feather", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "FEATHERS", "tooltip-feather", false);
	addItemBox("fireFeather", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "FIRE FEATHERS", "tooltip-feather", false);
	addItemBox("iceFeather", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ICE FEATHERS", "tooltip-feather", false);
	addItemBox("string", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "STRING", "tooltip-string", false);
	addItemBox("magicString", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "MAGIC STRING", "tooltip-magicString", false);
	addItemBox("bowBase", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "BOW BASE", "tooltip-bowBase", false);
	addItemBox("smallSnowballs", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "SMALL SNOWBALLS", "", false);
	addItemBox("mediumSnowball", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "MEDIUM SNOWBALL", "", false);
	addItemBox("largeSnowball", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "LARGE SNOWBALL", "", false);
	addItemBox("leftBranch", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "LEFT BRANCH", "", false);
	addItemBox("rightBranch", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "RIGHT BRANCH", "", false);
	addItemBox("chain", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "CHAIN", "tooltip-cemeterySkeleton", false);
	addItemBox("skeletonHead", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "CEMETERY SKULL", "tooltip-cemeterySkeleton", false);
	addItemBox("skeletonLeftArm", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "LEFT ARM", "tooltip-cemeterySkeleton", false);
	addItemBox("skeletonRightArm", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "RIGHT ARM", "tooltip-cemeterySkeleton", false);
	addItemBox("skeletonLeftLeg", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "LEFT LEG", "tooltip-cemeterySkeleton", false);
	addItemBox("skeletonRightLeg", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "RIGHT LEG", "tooltip-cemeterySkeleton", false);
	if (getItem("cookingUnlocked") == 0)
	{
		addItemBox("stew", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "STEW", "tooltip-stew", false);
		addItemBox("apple", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "APPLE", "tooltip-apple", false);
		addItemBox("storeBananas", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "BANANAS", "tooltip-storeBananas", false);
		addItemBox("rawChicken", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "RAW CHICKEN", "tooltip-rawChicken", false);
		addItemBox("cheese", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "CHEESE", "tooltip-cheese", false);
		addItemBox("honey", 0, "", "item-section-combat-1", _0x5C17, _0x5BDD, "HONEY", "tooltip-honey", false)
	};
	addItemBox("combatVial", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "EMPTY VIAL", "tooltip-combatVial", false);
	addItemBox("poisonCombatVial", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POISON VIAL", "tooltip-poisonCombatVial", false);
	addItemBox("arrow", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "ARROWS", "tooltip-arrow", false);
	addItemBox("fireArrow", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "FIRE ARROWS", "tooltip-fireArrow", false);
	addItemBox("iceArrow", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "ICE ARROWS", "tooltip-iceArrow", false);
	addItemBox("rustySword", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "RUSTY SWORD", "tooltip-rustySword", false);
	addItemBox("unlitTorch", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "UNLIT TORCH", "tooltip-unlitTorch", false);
	addItemBox("torch", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "TORCH", "tooltip-torch", false);
	addItemBox("stinger", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "STINGER", "tooltip-stinger", false);
	addItemBox("brokenStinger", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "STINGER", "tooltip-brokenStinger", false);
	addItemBox("ironDagger", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "IRON DAGGER", "tooltip-ironDagger", false);
	addItemBox("offhandIronDagger", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "OFFHAND DAGGER", "tooltip-offhandIronDagger", false);
	addItemBox("skeletonSword", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SKELETON SWORD", "tooltip-skeletonSword", false);
	addItemBox("bow", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BOW", "tooltip-bow", false);
	addItemBox("magicBow", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "MAGIC BOW", "tooltip-magicBow", false);
	addItemBox("scythe", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SCYTHE", "tooltip-scythe", false);
	addItemBox("trident", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "TRIDENT", "tooltip-trident", false);
	addItemBox("yetiLeftFoot", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "YETI\'S FOOT (L)", "tooltip-yetiLeftFoot", false);
	addItemBox("yetiRightFoot", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "YETI\'S FOOT (R)", "tooltip-yetiRightFoot", false);
	addItemBox("snakeskinMask", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SNAKESKIN MASK", "tooltip-snakeskinMask", false);
	addItemBox("snakeskinBody", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SNAKESKIN BODY", "tooltip-snakeskinBody", false);
	addItemBox("snakeskinLegs", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SNAKESKIN LEGS", "tooltip-snakeskinLegs", false);
	addItemBox("snakeskinBoots", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SNAKESKIN BOOTS", "tooltip-snakeskinBoots", false);
	addItemBox("snakeskinGloves", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SNAKESKIN GLOVES", "tooltip-snakeskinGloves", false);
	addItemBox("batSkinMask", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BATSKIN MASK", "tooltip-batSkinMask", false);
	addItemBox("batSkinBody", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BATSKIN BODY", "tooltip-batSkinBody", false);
	addItemBox("batSkinLegs", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BATSKIN LEGS", "tooltip-batSkinLegs", false);
	addItemBox("batSkinBoots", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BATSKIN BOOTS", "tooltip-batSkinBoots", false);
	addItemBox("batSkinGloves", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BATSKIN GLOVES", "tooltip-batSkinGloves", false);
	addItemBox("bearFurMask", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BEAR MASK", "tooltip-bearFurMask", false);
	addItemBox("bearFurBody", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BEAR BODY", "tooltip-bearFurBody", false);
	addItemBox("bearFurLegs", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BEAR LEGS", "tooltip-bearFurLegs", false);
	addItemBox("bearFurBoots", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BEAR BOOTS", "tooltip-bearFurBoots", false);
	addItemBox("bearFurGloves", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BEAR GLOVES", "tooltip-bearFurGloves", false);
	addItemBox("polarBearFurMask", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POLAR MASK", "tooltip-polarBearFurMask", false);
	addItemBox("polarBearFurBody", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POLAR BODY", "tooltip-polarBearFurBody", false);
	addItemBox("polarBearFurLegs", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POLAR LEGS", "tooltip-polarBearFurLegs", false);
	addItemBox("polarBearFurBoots", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POLAR BOOTS", "tooltip-polarBearFurBoots", false);
	addItemBox("polarBearFurGloves", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "POLAR GLOVES", "tooltip-polarBearFurGloves", false);
	addItemBox("flippers", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "FLIPPERS", "tooltip-flippers", false);
	addItemBox("woodenShield", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "WOOD SHIELD", "tooltip-woodenShield", false);
	addItemBox("skeletonShield", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "SKELETON SHIELD", "tooltip-skeletonShield", false);
	addItemBox("cemeterySkeletonShield1", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BROKEN SHIELD", "tooltip-cemeterySkeletonShieldBroken", false);
	addItemBox("cemeterySkeletonShield2", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BROKEN SHIELD", "tooltip-cemeterySkeletonShieldBroken", false);
	addItemBox("cemeterySkeletonShield3", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BROKEN SHIELD", "tooltip-cemeterySkeletonShieldBroken", false);
	addItemBox("cemeterySkeletonShield", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "CEMETERY SHIELD", "tooltip-cemeterySkeletonShieldBroken", false);
	addItemBox("boneAmulet", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BONE AMULET", "tooltip-boneAmulet", false);
	addItemBox("boneAmuletPlus", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "BONE AMULET+", "tooltip-boneAmuletPlus", false);
	addItemBox("invisibilityAmulet", 0, "", "item-section-combat-1", _0x5C34, _0x5BDD, "INVIS. AMULET", "tooltip-invisibilityAmulet", false);
	addItemBox("wand", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "WAND", "tooltip-wand", false);
	addItemBox("staff", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "MAGIC STAFF", "tooltip-staff", false);
	addItemBox("reaperHood", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "REAPER HOOD", "tooltip-reaperHood", false);
	addItemBox("reaperBody", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "REAPER BODY", "tooltip-reaperBody", false);
	addItemBox("reaperLegs", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "REAPER SKIRT", "tooltip-reaperLegs", false);
	addItemBox("reaperBoots", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "REAPER BOOTS", "tooltip-reaperBoots", false);
	addItemBox("reaperGloves", 0, "", "item-section-combat-1", _0x5BC0, _0x5BA3, "REAPER GLOVES", "tooltip-reaperGloves", false);
	addItemBox("cooldownRing1", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "CD RING (1)", "tooltip-cooldownRing1", false);
	addItemBox("energyRing1", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ENERGY RING (1)", "tooltip-energyRing1", false);
	addItemBox("manaRing1", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "MANA RING (1)", "tooltip-manaRing1", false);
	addItemBox("cooldownRing2", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "CD RING (2)", "tooltip-cooldownRing2", false);
	addItemBox("energyRing2", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ENERGY RING (2)", "tooltip-energyRing2", false);
	addItemBox("manaRing2", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "MANA RING (2)", "tooltip-manaRing2", false);
	addItemBox("cooldownRing3", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "CD RING (3)", "tooltip-cooldownRing3", false);
	addItemBox("energyRing3", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "ENERGY RING (3)", "tooltip-energyRing3", false);
	addItemBox("manaRing3", 0, "", "item-section-combat-1", _0x5BFA, _0x5BDD, "MANA RING (3)", "tooltip-manaRing3", false);
	addItemBox("convertMagic", 1, "", "item-section-magic-1", "#0066cc", "#0066cc", "CONVERT", "tooltip-convertMagic", false);
	addItemBox("manaStars", "manaStars", "", "item-section-magic-1", "#002233", "#80d4ff", "MANA STARS", "tooltip-manaStars", false);
	addItemBox("smallManaStar", "smallManaStar", "", "item-section-magic-1", "#002233", "#80d4ff", "MANA STAR", "tooltip-smallManaStar", false);
	addItemBox("mediumManaStar", "mediumManaStar", "", "item-section-magic-1", "#002233", "#80d4ff", "MANA STAR", "tooltip-mediumManaStar", false);
	addItemBox("largeManaStar", "largeManaStar", "", "item-section-magic-1", "#002233", "#80d4ff", "MANA STAR", "tooltip-largeManaStar", false);
	addItemBox("hugeManaStar", "hugeManaStar", "", "item-section-magic-1", "#002233", "#80d4ff", "MANA STAR", "tooltip-hugeManaStar", false);
	addItemBox("spellScrollHeal", "spellScrollHeal", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollHeal", false);
	addItemBox("spellScrollPoison", "spellScrollPoison", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollPoison", false);
	addItemBox("spellScrollReflect", "spellScrollReflect", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollReflect", false);
	addItemBox("spellScrollFire", "spellScrollReflect", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollFire", false);
	addItemBox("spellScrollTeleport", "spellScrollTeleport", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollTeleport", false);
	addItemBox("spellScrollFreeze", "spellScrollFreeze", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollFreeze", false);
	addItemBox("spellScrollGhostScan", "spellScrollGhostScan", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollGhostScan", false);
	addItemBox("spellScrollInvisibility", "spellScrollInvisibility", "", "item-section-magic-1", "#002233", "#80d4ff", "SPELL SCROLL", "tooltip-spellScrollInvisibility", false);
	addItemBox("heal", "heal", "", "item-section-magic-1", "#002233", "#80d4ff", "HEAL", "tooltip-heal", false);
	addItemBox("poison", "poison", "", "item-section-magic-1", "#002233", "#80d4ff", "POISON", "tooltip-poison", false);
	addItemBox("reflect", "reflect", "", "item-section-magic-1", "#002233", "#80d4ff", "REFLECT", "tooltip-reflect", false);
	addItemBox("fire", "fire", "", "item-section-magic-1", "#002233", "#80d4ff", "FIRE", "tooltip-fire", false);
	addItemBox("teleport", "teleport", "", "item-section-magic-1", "#002233", "#80d4ff", "TELEPORT", "tooltip-teleport", false);
	addItemBox("freeze", "freeze", "", "item-section-magic-1", "#002233", "#80d4ff", "FREEZE", "tooltip-freeze", false);
	addItemBox("ghostScan", "ghostScan", "", "item-section-magic-1", "#002233", "#80d4ff", "GHOST SCAN", "tooltip-ghostScan", false);
	addItemBox("invisibility", "invisibility", "", "item-section-magic-1", "#002233", "#80d4ff", "INVISIBILITY", "tooltip-invisibility", false);
	addItemBox("transformLog", "transformLog", "", "convertMagic-section", "#002233", "#80d4ff", "TRANSFORM LOG", "tooltip-transformLog", true);
	addItemBox("needle", 0, "", "convertMagic-section", "#002233", "#80d4ff", "NEEDLE", "tooltip-needle", false);
	addItemBox("daggerBlade", 0, "", "convertMagic-section", "#002233", "#80d4ff", "DAGGER BLADE", "tooltip-daggerBlade", false);
	addItemBox("daggerHandle", 0, "", "convertMagic-section", "#002233", "#80d4ff", "DAGGER HANDLE", "tooltip-daggerHandle", false);
	addItemBox("skeletonSwordMetal", 0, "", "convertMagic-section", "#002233", "#80d4ff", "SWORD METAL", "tooltip-skeletonSwordMetal", false);
	addItemBoxMining("miner", "", "item-section-mining-1", _0x5B4C, "grey", "MINER", "tooltip-miner", false);
	addItemBoxMining("drills", "", "item-section-mining-1", _0x5B4C, "grey", "DRILLS", "tooltip-drills", false);
	addItemBoxMining("crushers", "", "item-section-mining-1", _0x5B4C, "grey", "CRUSHERS", "tooltip-crushers", false);
	addItemBoxMining("giantDrills", "", "item-section-mining-1", _0x5B4C, "grey", "GIANT DRILLS", "tooltip-giantDrills", false);
	addItemBoxMining("excavators", "", "item-section-mining-1", _0x5B4C, "grey", "EXCAVATORS", "tooltip-excavators", false);
	addItemBox("rocket", 1, "", "item-section-mining-1", "#333333", "grpey", "ROCKET", "tooltip-rocket", false);
	addItemBox("diamond_verydark", 1, "", "item-section-mining-1", "#333333", "grey", "GEM LIST", "tooltip-none", false);
	addItemBox("gemList2", 1, "", "item-section-mining-1", "#333333", "grey", "GEM/PRISM LIST", "tooltip-none", false);
	addItemBox("gemList3", 1, "", "item-section-mining-1", "#333333", "grey", "COLLECTION", "tooltip-none", false);
	addItemBox("stardustPickaxe", 1, "", "item-section-mining-1", "#333333", "grey", "PICKAXE", "tooltip-stardustPickaxe", false);
	addItemBox("sapphireStardustPickaxe", 1, "", "item-section-mining-1", "#333333", "grey", "PICKAXE", "tooltip-stardustPickaxe", false);
	addItemBox("emeraldStardustPickaxe", 1, "", "item-section-mining-1", "#333333", "grey", "PICKAXE", "tooltip-stardustPickaxe", false);
	addItemBox("rubyStardustPickaxe", 1, "", "item-section-mining-1", "#333333", "grey", "PICKAXE", "tooltip-stardustPickaxe", false);
	addItemBox("diamondStardustPickaxe", 1, "", "item-section-mining-1", "#333333", "grey", "PICKAXE", "tooltip-stardustPickaxe", false);
	addItemBox("shovel", 1, "", "item-section-mining-1", "#333333", "grey", "SHOVEL", "tooltip-shovel", false);
	addItemBox("sapphireShovel", 1, "", "item-section-mining-1", "#333333", "grey", "SHOVEL", "tooltip-sapphireShovel", false);
	addItemBox("emeraldShovel", 1, "", "item-section-mining-1", "#333333", "grey", "SHOVEL", "tooltip-emeraldShovel", false);
	addItemBox("rubyShovel", 1, "", "item-section-mining-1", "#333333", "grey", "SHOVEL", "tooltip-rubyShovel", false);
	addItemBox("diamondShovel", 1, "", "item-section-mining-1", "#333333", "grey", "SHOVEL", "tooltip-diamondShovel", false);
	addItemBox("oilStorage1", 1, "", "item-section-mining-1", "#333333", "grey", "OIL STORAGE I", "", false);
	addItemBox("oilStorage2", 1, "", "item-section-mining-1", "#333333", "grey", "OIL STORAGE II", "", false);
	addItemBox("oilStorage3", 1, "", "item-section-mining-1", "#333333", "grey", "OIL STORAGE III", "", false);
	addItemBox("oilStorage4", 1, "", "item-section-mining-1", "#333333", "grey", "OIL STORAGE VI", "", false);
	addItemBox("bronzeOilWell", 1, "", "item-section-mining-1", "#333333", "grey", "OIL WELL", "", false);
	addItemBox("ironOilWell", 1, "", "item-section-mining-1", "#333333", "grey", "OIL WELL", "", false);
	addItemBox("silverOilWell", 1, "", "item-section-mining-1", "#333333", "grey", "OIL WELL", "", false);
	addItemBox("goldOilWell", 1, "", "item-section-mining-1", "#333333", "grey", "OIL WELL", "", false);
	addItemBox("promethiumOilWell", 1, "", "item-section-mining-1", "#333333", "grey", "OIL WELL", "", false);
	addItemBox("darkCrystal", 0, "", "item-section-mining-1", "#333333", "grey", "DARK CRYSTAL", "tooltip-darkCrystal", false);
	addItemBox("darkCrystalUsed", 0, "", "item-section-mining-1", "#333333", "grey", "DARK CRYSTAL", "tooltip-darkCrystalUsed", false);
	addItemBox("cyanCrystal", 0, "", "item-section-mining-1", "#333333", "grey", "SKY CRYSTAL", "tooltip-colorCrystal", false);
	addItemBox("redCrystal", 0, "", "item-section-mining-1", "#333333", "grey", "LAVA CRYSTAL", "tooltip-colorCrystal", false);
	addItemBox("blueCrystal", 0, "", "item-section-mining-1", "#333333", "grey", "OCEAN CRYSTAL", "tooltip-colorCrystal", false);
	addItemBox("carePackage1", 0, "", "item-section-mining-1", "#333333", "grey", "CARE PACKAGE", "tooltip-carePackage", false);
	addItemBox("sapphire", 0, "", "item-section-mining-1", "#333333", "grey", "SAPPHIRE", "tooltip-gem", false);
	addItemBox("emerald", 0, "", "item-section-mining-1", "#333333", "grey", "EMERALD", "tooltip-gem", false);
	addItemBox("ruby", 0, "", "item-section-mining-1", "#333333", "grey", "RUBY", "tooltip-gem", false);
	addItemBox("diamond", 0, "", "item-section-mining-1", "#333333", "grey", "DIAMOND", "tooltip-gem", false);
	addItemBox("bloodDiamond", 0, "", "item-section-mining-1", "#333333", "grey", "BLOOD DIAMOND", "tooltip-gem", false);
	addItemBox("smallStardustPrism", 0, "", "item-section-mining-1", "#333333", "grey", "SMALL PRISM", "tooltip-smallStardustPrism", false);
	addItemBox("mediumStardustPrism", 0, "", "item-section-mining-1", "#333333", "grey", "MEDIUM PRISM", "tooltip-mediumStardustPrism", false);
	addItemBox("largeStardustPrism", 0, "", "item-section-mining-1", "#333333", "grey", "LARGE PRISM", "tooltip-largeStardustPrism", false);
	addItemBox("hugeStardustPrism", 0, "", "item-section-mining-1", "#333333", "grey", "HUGE PRISM", "tooltip-hugeStardustPrism", false);
	addItemBox("sand", 0, "", "item-section-mining-1", "#333333", "grey", "SAND", "tooltip-sand", false);
	addItemBox("stone", 0, "", "item-section-mining-1", "#333333", "grey", "STONE", "tooltip-stone", false);
	addItemBox("copper", 0, "", "item-section-mining-1", "#333333", "grey", "COPPER", "tooltip-copper", false);
	addItemBox("iron", 0, "", "item-section-mining-1", "#333333", "grey", "IRON", "tooltip-iron", false);
	addItemBox("silver", 0, "", "item-section-mining-1", "#333333", "grey", "SILVER", "tooltip-silver", false);
	addItemBox("gold", 0, "", "item-section-mining-1", "#333333", "grey", "GOLD", "tooltip-gold", false);
	addItemBox("promethium", 0, "", "item-section-mining-1", "#333333", "grey", "PROMETHIUM", "tooltip-promethium", false);
	addItemBox("titanium", 0, "", "item-section-mining-1", "#333333", "grey", "TITANIUM", "tooltip-titanium", false);
	addItemBox("moonstone", 0, "", "item-section-mining-1", "#333333", "grey", "MOONSTONE", "tooltip-moonstone", false);
	addItemBox("chisel", 1, "", "item-section-mining-1", "#0d0d0d", "grey", "CHISEL", "tooltip-chisel", false);
	addItemBox("sapphireChisel", 1, "", "item-section-mining-1", "#0d0d0d", "grey", "CHISEL", "tooltip-sapphireChisel", false);
	addItemBox("emeraldChisel", 1, "", "item-section-mining-1", "#0d0d0d", "grey", "CHISEL", "tooltip-emeraldChisel", false);
	addItemBox("rubyChisel", 1, "", "item-section-mining-1", "#0d0d0d", "grey", "CHISEL", "tooltip-rubyChisel", false);
	addItemBox("diamondChisel", 1, "", "item-section-mining-1", "#0d0d0d", "grey", "CHISEL", "tooltip-diamondChisel", false);
	addItemBox("ringMould", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "RING MOULD", "tooltip-ringMould", false);
	addItemBox("blueGeode", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "BLUE GEODE", "tooltip-geode", false);
	addItemBox("greenGeode", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "GREEN GEODE", "tooltip-geode", false);
	addItemBox("redGeode", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "RED GEODE", "tooltip-geode", false);
	addItemBox("purpleGeode", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "PURPLE GEODE", "tooltip-geode", false);
	addItemBox("limeQuartzMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-limeQuartzMineral", false);
	addItemBox("jadeMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-jadeMineral", false);
	addItemBox("amethystMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-amethystMineral", false);
	addItemBox("blueMarbleMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-blueMarbleMineral", false);
	addItemBox("limoniteMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-limoniteMineral", false);
	addItemBox("tashmarineMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-tashmarineMineral", false);
	addItemBox("denseMarbleMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-denseMarbleMineral", false);
	addItemBox("fluoriteMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-fluoriteMineral", false);
	addItemBox("purpleQuartzMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-purpleQuartzMineral", false);
	addItemBox("crystalPrismeMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-crystalPrismeMineral", false);
	addItemBox("amberMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-amberMineral", false);
	addItemBox("tanzaniteMineral", 0, "", "item-section-mining-1", "#0d0d0d", "grey", "MINERAL", "tooltip-tanzaniteMineral", false);
	addItemBox("stardustHammer", 0, "", "item-section-crafting-1", "#595959", "grey", "HAMMER", "tooltip-stardustHammer", false);
	addItemBox("sapphireStardustHammer", 0, "", "item-section-crafting-1", "#595959", "grey", "HAMMER", "tooltip-stardustHammer", false);
	addItemBox("emeraldStardustHammer", 0, "", "item-section-crafting-1", "#595959", "grey", "HAMMER", "tooltip-stardustHammer", false);
	addItemBox("rubyStardustHammer", 0, "", "item-section-crafting-1", "#595959", "grey", "HAMMER", "tooltip-stardustHammer", false);
	addItemBox("diamondStardustHammer", 0, "", "item-section-crafting-1", "#595959", "grey", "HAMMER", "tooltip-stardustHammer", false);
	addItemBox("stoneFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("bronzeFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("ironFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("silverFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("goldFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("promethiumFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("titaniumFurnace", 0, "", "item-section-crafting-1", "#595959", "grey", "FURNACE", "tooltip-furnace", false);
	addItemBox("charcoalFoundry", 0, "", "item-section-crafting-1", "#595959", "grey", "FOUNDRY", "tooltip-charcoalFoundry", false);
	addItemBox("charcoal", 0, "", "item-section-crafting-1", "#595959", "grey", "CHARCOAL", "tooltip-charcoal", false);
	addItemBox("lava", 0, "", "item-section-crafting-1", "#595959", "grey", "LAVA", "tooltip-lava", false);
	addItemBox("brewingKitMould", 0, "", "item-section-crafting-1", "#595959", "grey", "MOULD", "tooltip-mould", false);
	addItemBox("wrenchMould", 0, "", "item-section-crafting-1", "#595959", "grey", "MOULD", "tooltip-mould", false);
	addItemBox("trowelMould", 0, "", "item-section-crafting-1", "#595959", "grey", "MOULD", "tooltip-mould", false);
	addItemBox("chainsawMould", 0, "", "item-section-crafting-1", "#595959", "grey", "MOULD", "tooltip-mould", false);
	addItemBox("houseBlueprint", 0, "", "item-section-crafting-1", "#595959", "grey", "BLUEPRINTS", "tooltip-bluePrints", false);
	addItemBox("museumBlueprint", 0, "", "item-section-crafting-1", "#595959", "grey", "BLUEPRINTS", "tooltip-bluePrints", false);
	addItemBox("sapphireGlassHand", 0, "", "item-section-crafting-1", "#595959", "grey", "GLASS HAND", "tooltip-sapphireGlassHand", false);
	addItemBox("emeraldGlassHand", 0, "", "item-section-crafting-1", "#595959", "grey", "GLASS HAND", "tooltip-emeraldGlassHand", false);
	addItemBox("rubyGlassHand", 0, "", "item-section-crafting-1", "#595959", "grey", "GLASS HAND", "tooltip-rubyGlassHand", false);
	addItemBox("tractorTire", 0, "", "item-section-crafting-1", "#333333", "grey", "TRACTOR TIRE", "tooltip-tractorTire", false);
	addItemBox("ironBucket", 0, "", "item-section-crafting-1", "#333333", "grey", "SILVER BUCKET", "tooltip-ironBucket", false);
	addItemBox("glass", 0, "", "item-section-crafting-1", "#333333", "grey", "GLASS", "tooltip-glass", false);
	addItemBox("bronzeBars", 0, "", "item-section-crafting-1", "#333333", "grey", "BRONZE BAR", "tooltip-bronzeBars", false);
	addItemBox("ironBars", 0, "", "item-section-crafting-1", "#333333", "grey", "IRON BAR", "tooltip-ironBars", false);
	addItemBox("silverBars", 0, "", "item-section-crafting-1", "#333333", "grey", "SILVER BAR", "tooltip-silverBars", false);
	addItemBox("goldBars", 0, "", "item-section-crafting-1", "#333333", "grey", "GOLD BAR", "tooltip-goldBars", false);
	addItemBox("promethiumBars", 0, "", "item-section-crafting-1", "#333333", "grey", "PROMETHIUM BAR", "tooltip-promethiumBars", false);
	addItemBox("titaniumBars", 0, "", "item-section-crafting-1", "#333333", "grey", "TITANIUM BAR", "tooltip-titaniumBars", false);
	addItemBox("treeList", 1, "", "item-section-woodcutting-1", "#003300", "green", "TREE LIST", "tooltip-treeList", true);
	addItemBox("axe", 1, "", "item-section-woodcutting-1", "#003300", "green", "AXE", "tooltip-axe", false);
	addItemBox("sapphireAxe", 1, "", "item-section-woodcutting-1", "#003300", "green", "AXE", "tooltip-axe", false);
	addItemBox("emeraldAxe", 1, "", "item-section-woodcutting-1", "#003300", "green", "AXE", "tooltip-axe", false);
	addItemBox("rubyAxe", 1, "", "item-section-woodcutting-1", "#003300", "green", "AXE", "tooltip-axe", false);
	addItemBox("diamondAxe", 1, "", "item-section-woodcutting-1", "#003300", "green", "AXE", "tooltip-axe", false);
	addItemBox("chainsaw", 1, "", "item-section-woodcutting-1", "#003300", "green", "CHAINSAW", "tooltip-chainsaw", false);
	addItemBox("sapphireChainsaw", 1, "", "item-section-woodcutting-1", "#003300", "green", "CHAINSAW", "tooltip-chainsaw", false);
	addItemBox("emeraldChainsaw", 1, "", "item-section-woodcutting-1", "#003300", "green", "CHAINSAW", "tooltip-chainsaw", false);
	addItemBox("rubyChainsaw", 1, "", "item-section-woodcutting-1", "#003300", "green", "CHAINSAW", "tooltip-chainsaw", false);
	addItemBox("diamondChainsaw", 1, "", "item-section-woodcutting-1", "#003300", "green", "CHAINSAW", "tooltip-chainsaw", false);
	addItemBox("lumberJack", 1, "", "item-section-woodcutting-1", "#004d00", "green", "LUMBERJACK", "tooltip-lumberJack", false);
	addItemBox("cockroach", 0, "", "item-section-woodcutting-1", "#004d00", "green", "GIANT COCKROACH", "tooltip-cockroach", false);
	addItemBox("goldenCockroach", 0, "", "item-section-woodcutting-1", "#004d00", "green", "GIANT COCKROACH", "tooltip-goldenCockroach", false);
	addItemBox("logs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "LOGS", "tooltip-logs", false);
	addItemBox("oakLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "OAK LOGS", "tooltip-oakLogs", false);
	addItemBox("willowLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "WILLOW LOGS", "tooltip-willowLogs", false);
	addItemBox("bambooLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "BAMBOO", "tooltip-bambooLogs", false);
	addItemBox("mapleLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "MAPLE", "tooltip-mapleLogs", false);
	addItemBox("lavaLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "LAVA LOGS", "tooltip-lavaLogs", false);
	addItemBox("pineLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "PINE LOGS", "tooltip-pineLogs", false);
	addItemBox("stardustLogs", 0, "", "item-section-woodcutting-1", "#004d00", "green", "STARDUST", "tooltip-stardustLogs", false);
	addItemBox("bob", 0, "", "item-section-farming-1", "#003300", "green", "BOB", "tooltip-bob", true);
	addItemBox("planter", 0, "", "item-section-farming-1", "#003300", "green", "PLANTER", "tooltip-planter", false);
	addItemBox("rakeHead", 0, "", "item-section-farming-1", "#003300", "green", "RAKE HEAD", "tooltip-rakeHead", false);
	addItemBox("rake", 0, "", "item-section-farming-1", "#003300", "green", "RAKE", "tooltip-rake", false);
	addItemBox("sapphireRake", 0, "", "item-section-farming-1", "#003300", "green", "RAKE", "tooltip-rake", false);
	addItemBox("emeraldRake", 0, "", "item-section-farming-1", "#003300", "green", "RAKE", "tooltip-rake", false);
	addItemBox("rubyRake", 0, "", "item-section-farming-1", "#003300", "green", "RAKE", "tooltip-rake", false);
	addItemBox("diamondRake", 0, "", "item-section-farming-1", "#003300", "green", "RAKE", "tooltip-rake", false);
	addItemBox("trowel", 0, "", "item-section-farming-1", "#003300", "green", "TROWEL", "tooltip-trowel", false);
	addItemBox("sapphireTrowel", 0, "", "item-section-farming-1", "#003300", "green", "TROWEL", "tooltip-trowel", false);
	addItemBox("emeraldTrowel", 0, "", "item-section-farming-1", "#003300", "green", "TROWEL", "tooltip-trowel", false);
	addItemBox("rubyTrowel", 0, "", "item-section-farming-1", "#003300", "green", "TROWEL", "tooltip-trowel", false);
	addItemBox("diamondTrowel", 0, "", "item-section-farming-1", "#003300", "green", "TROWEL", "tooltip-trowel", false);
	addItemBox("seedList", 1, "", "item-section-farming-1", "#003300", "green", "SEED LIST", "", true);
	addItemBox("bonemealBin", "bonemeal", "", "item-section-farming-1", "#003300", "green", "BONEMEAL", "tooltip-bonemeal", false);
	addItemBox("sapphireBonemealBin", "bonemeal", "", "item-section-farming-1", "#003300", "green", "BONEMEAL", "tooltip-bonemeal", false);
	addItemBox("emeraldBonemealBin", "bonemeal", "", "item-section-farming-1", "#003300", "green", "BONEMEAL", "tooltip-bonemeal", false);
	addItemBox("rubyBonemealBin", "bonemeal", "", "item-section-farming-1", "#003300", "green", "BONEMEAL", "tooltip-bonemeal", false);
	addItemBox("diamondBonemealBin", "bonemeal", "", "item-section-farming-1", "#003300", "green", "BONEMEAL", "tooltip-bonemeal", false);
	addItemBox("treeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "TREE SEED", "tooltip-treeSeeds", false);
	addItemBox("oakTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "OAK SEED", "tooltip-oakTreeSeeds", false);
	addItemBox("willowTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "WILLOW SEED", "tooltip-willowTreeSeeds", false);
	addItemBox("bambooTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "BAMBOO SEED", "tooltip-bambooTreeSeeds", false);
	addItemBox("appleTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "APPLE SEED", "tooltip-appleTreeSeeds", false);
	addItemBox("mapleTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "MAPLE SEED", "tooltip-mapleTreeSeeds", false);
	addItemBox("lavaTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "LAVA TREE SEED", "tooltip-lavaTreeSeeds", false);
	addItemBox("bananaTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "BANANA SEED", "tooltip-bananaTreeSeeds", false);
	addItemBox("pineTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "PINE TREE SEED", "tooltip-pineTreeSeeds", false);
	addItemBox("stardustTreeSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "STARDUST SEED", "tooltip-stardustTreeSeeds", false);
	addItemBox("dottedGreenLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "DOTTED LEAF", "tooltip-dottedGreenLeafSeeds", false);
	addItemBox("greenLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "GREEN LEAF", "tooltip-greenLeafSeeds", false);
	addItemBox("limeLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "LIME LEAF", "tooltip-limeLeafSeeds", false);
	addItemBox("goldLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "GOLD LEAF", "tooltip-goldLeafSeeds", false);
	addItemBox("crystalLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "CRYSTAL LEAF", "tooltip-crystalLeafSeeds", false);
	addItemBox("stripedGoldLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "GOLD STRIPED", "tooltip-stripedGoldLeafSeeds", false);
	addItemBox("stripedCrystalLeafSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "CRYSTAL STRIPED", "tooltip-stripedCrystalLeafSeeds", false);
	addItemBox("redMushroomSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "MUSHROOMS", "tooltip-redMushroomSeeds", false);
	addItemBox("blewitMushroomSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "BLEWIT MUSH.", "tooltip-blewitMushroomSeeds", false);
	addItemBox("stardustSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "STARDUST SEEDS", "tooltip-stardustSeeds", false);
	addItemBox("carrotSeeds", 0, "", "item-section-farming-1", "#004d00", "green", "CARROT SEEDS", "tooltip-carrotSeeds", false);
	addItemBox("brewingKit", 1, "", "item-section-brewing-1", "#4d004d", "purple", "BREWING KIT", "tooltip-brewingKit", false);
	addItemBox("sapphireBrewingKit", 1, "", "item-section-brewing-1", "#4d004d", "purple", "BREWING KIT", "tooltip-brewingKit", false);
	addItemBox("emeraldBrewingKit", 1, "", "item-section-brewing-1", "#4d004d", "purple", "BREWING KIT", "tooltip-brewingKit", false);
	addItemBox("rubyBrewingKit", 1, "", "item-section-brewing-1", "#4d004d", "purple", "BREWING KIT", "tooltip-brewingKit", false);
	addItemBox("diamondBrewingKit", 1, "", "item-section-brewing-1", "#4d004d", "purple", "BREWING KIT", "tooltip-brewingKit", false);
	addItemBox("vial", 0, "", "item-section-brewing-1", "#4d004d", "purple", "SMALL VIALS", "", false);
	addItemBox("largeVial", 0, "", "item-section-brewing-1", "#4d004d", "purple", "LARGE VIALS", "", false);
	addItemBox("dottedGreenLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "DOTTED LEAF", "tooltip-dottedGreenLeaf", false);
	addItemBox("greenLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "GREEN LEAF", "tooltip-greenLeaf", false);
	addItemBox("limeLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "LIME LEAF", "tooltip-limeLeaf", false);
	addItemBox("goldLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "GOLD LEAF", "tooltip-goldLeaf", false);
	addItemBox("crystalLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "CRYSTAL LEAF", "tooltip-crystalLeaf", false);
	addItemBox("stripedGoldLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "STRIPED GOLD", "tooltip-stripedGoldLeaf", false);
	addItemBox("stripedCrystalLeaf", 0, "", "item-section-brewing-1", "#004d00", "green", "STRIPED CRYSTAL", "tooltip-stripedCrystalLeaf", false);
	addItemBox("redMushroom", 0, "", "item-section-brewing-1", "#004d00", "green", "MUSHROOM", "tooltip-redMushroom", false);
	addItemBox("blewitMushroom", 0, "", "item-section-brewing-1", "#004d00", "green", "BLEWIT MUSH.", "tooltip-blewitMushroom", false);
	addItemBox("strangeLeafFix", 0, "", "item-section-brewing-1", "#004d00", "green", "STRANGE LEAF", "tooltip-strangeLeaf", false);
	addItemBox("stardustPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "STARDUST POTION", "tooltip-stardustPotion", false);
	addItemBox("sandPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "SAND POTION", "", false);
	addItemBox("cookingBoostPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "COOKING BOOST", "", false);
	addItemBox("combatCooldownPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "COMB. COOLDOWN", "", false);
	addItemBox("compostPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "COMPOST POTION", "", false);
	addItemBox("oilPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "OIL POTION", "", false);
	addItemBox("bonePotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "BONE POTION", "", false);
	addItemBox("treeStarterPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "TREE STARTER", "", false);
	addItemBox("repelPotion1", 0, "", "item-section-brewing-1", "#4d004d", "purple", "REPEL POTION", "", false);
	addItemBox("barPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "BAR POTION", "", false);
	addItemBox("sapphireStardustPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "SAPPHIRE STAR.", "", false);
	addItemBox("largeManaPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "MANA POTION", "", false);
	addItemBox("largeStardustPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "STARDUST POTION", "", false);
	addItemBox("largeFurnacePotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "FURNACE POTION", "", false);
	addItemBox("largePiratePotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "PIRATE POTION", "", false);
	addItemBox("largeEmeraldStardustPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "EMERALD STAR.", "", false);
	addItemBox("largeRocketSpeedPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "ROCKET SPEED", "", false);
	addItemBox("repelPotion2", 0, "", "item-section-brewing-1", "#4d004d", "purple", "REPEL POTION", "", false);
	addItemBox("largeBarPotion", 0, "", "item-section-brewing-1", "#4d004d", "purple", "LARGE BAR POT.", "", false);
	addItemBox("smallFishingNet", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "SMALL NET", "tooltip-smallFishingNet", false);
	addItemBox("sapphireSmallFishingNet", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "SMALL NET", "tooltip-smallFishingNet", false);
	addItemBox("emeraldSmallFishingNet", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "SMALL NET", "tooltip-smallFishingNet", false);
	addItemBox("rubySmallFishingNet", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "SMALL NET", "tooltip-smallFishingNet", false);
	addItemBox("diamondSmallFishingNet", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "SMALL NET", "tooltip-smallFishingNet", false);
	addItemBox("fishingRod", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "FISHING ROD", "tooltip-fishingRod", false);
	addItemBox("sapphireFishingRod", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "FISHING ROD", "tooltip-fishingRod", false);
	addItemBox("emeraldFishingRod", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "FISHING ROD", "tooltip-fishingRod", false);
	addItemBox("rubyFishingRod", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "FISHING ROD", "tooltip-fishingRod", false);
	addItemBox("diamondFishingRod", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "FISHING ROD", "tooltip-fishingRod", false);
	addItemBox("harpoon", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "HARPOON", "tooltip-harpoon", false);
	addItemBox("sapphireHarpoon", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "HARPOON", "tooltip-harpoon", false);
	addItemBox("emeraldHarpoon", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "HARPOON", "tooltip-harpoon", false);
	addItemBox("rubyHarpoon", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "HARPOON", "tooltip-harpoon", false);
	addItemBox("diamondHarpoon", 1, "", "item-section-fishing-1", "#00061a", "#00124d", "HARPOON", "tooltip-harpoon", false);
	addItemBox("oxygenTank", 0, "", "item-section-fishing-1", "#00061a", "#00124d", "OXYGEN TANK", "tooltip-oxygenTank", false);
	addItemBox("rowBoat", 0, "", "item-section-fishing-1", "#00061a", "#00124d", "ROW BOAT", "tooltip-rowBoat", false);
	addItemBox("canoeBoat", 0, "", "item-section-fishing-1", "#00061a", "#00124d", "CANOE", "tooltip-canoeBoat", false);
	addItemBox("specialBait", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "SPECIAL BAIT", "tooltip-specialBait", false);
	addItemBox("specialFish", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "SPECIAL FISH", "tooltip-specialFish", false);
	addItemBox("oyster", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "OYSTER", "tooltip-oyster", false);
	addItemBox("specialOyster", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "OYSTER", "tooltip-specialOyster", false);
	addItemBox("pearl", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "PEARL", "tooltip-pearl", false);
	addItemBox("giantPearl", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "GIANT PEARL", "tooltip-giantPearl", false);
	addItemBox("rarePearl", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "PEARL", "tooltip-rarePearl", false);
	addItemBox("rareGiantPearl", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "GIANT PEARL", "tooltip-rareGiantPearl", false);
	addItemBox("sharkTooth", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "SHARK TOOTH", "tooltip-sharkTooth", false);
	addItemBox("rowBoatBlueprints", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "ROW BOAT", "tooltip-rowBoatBlueprints", false);
	addItemBox("canoeBoatBlueprints", 0, "", "item-section-fishing-1", "#006666", "#004d4d", "CANOE", "tooltip-canoeBoatBlueprints", false);
	addItemBox("smallSeaShell", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SMALL SHELL", "tooltip-smallSeaShell", false);
	addItemBox("mediumSeaShell", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "MEDIUM SHELL", "tooltip-mediumSeaShell", false);
	addItemBox("largeSeaShell", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "LARGE SHELL", "tooltip-largeSeaShell", false);
	addItemBox("seaweed", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SEAWEED", "tooltip-seaweed", false);
	addItemBox("fishBones", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "FISH BONES", "tooltip-fishBones", false);
	addItemBox("rawShrimp", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SHRIMP", "tooltip-rawShrimp", false);
	addItemBox("rawAnchovy", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW ANCHOVY", "tooltip-rawAnchovy", false);
	addItemBox("rawSardine", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SARDINE", "tooltip-rawSardine", false);
	addItemBox("rawCrab", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW CRAB", "tooltip-rawCrab", false);
	addItemBox("rawPiranha", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW PIRANHA", "tooltip-rawPiranha", false);
	addItemBox("rawTrout", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW TROUT", "tooltip-rawTrout", false);
	addItemBox("rawSalmon", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SALMON", "tooltip-rawSalmon", false);
	addItemBox("rawEel", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW EEL", "tooltip-rawEel", false);
	addItemBox("rawSeaTurtle", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SEA TURTLE", "tooltip-rawSeaTurtle", false);
	addItemBox("rawRainbowFish", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW RAINBOW FISH", "tooltip-rawRainbowFish", false);
	addItemBox("rawTuna", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW TUNA", "tooltip-rawTuna", false);
	addItemBox("rawSwordfish", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SWORDFISH", "tooltip-rawSwordfish", false);
	addItemBox("rawMantaRay", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW MANTA RAY", "tooltip-rawMantaRay", false);
	addItemBox("rawShark", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW SHARK", "tooltip-rawShark", false);
	addItemBox("rawWhale", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAW WHALE", "tooltip-rawWhale", false);
	addItemBox("shrimp", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SHRIMP", "tooltip-shrimp", false);
	addItemBox("anchovy", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "ANCHOVY", "tooltip-anchovy", false);
	addItemBox("sardine", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SARDINE", "tooltip-sardine", false);
	addItemBox("crab", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "CRAB", "tooltip-crab", false);
	addItemBox("piranha", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "PIRANHA", "tooltip-piranha", false);
	addItemBox("trout", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "TROUT", "tooltip-trout", false);
	addItemBox("salmon", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SALMON", "tooltip-salmon", false);
	addItemBox("eel", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "EEL", "tooltip-eel", false);
	addItemBox("seaTurtle", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SEA TURTLE", "tooltip-seaTurtle", false);
	addItemBox("rainbowFish", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "RAINBOW FISH", "tooltip-rainbowFish", false);
	addItemBox("tuna", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "TUNA", "tooltip-tuna", false);
	addItemBox("swordfish", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SWORDFISH", "tooltip-swordfish", false);
	addItemBox("mantaRay", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "MANTA RAY", "tooltip-mantaRay", false);
	addItemBox("shark", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "SHARK", "tooltip-shark", false);
	addItemBox("whale", 0, "", "item-section-fishing-1", "#001e80", "#0036e6", "WHALE", "tooltip-whale", false);
	if (getItemString("home") != "none")
	{
		addItemBox("donorCoins", 0, "", "item-section-home-1", "green", "lime", "DONOR COINS", "tooltip-donorCoins", false)
	};
	addItemBox("stardust1000", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "STARDUST PACK", "tooltip-stardust1000", false);
	addItemBox("researcher", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "RESEARCHER", "tooltip-researcher", false);
	addItemBox("museum", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "MUSEUM", "tooltip-museum", false);
	addItemBox("pirate", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "PIRATE", "tooltip-pirate", false);
	addItemBox("treasureMap", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "TREASURE MAP", "tooltip-treasureMap", false);
	addItemBox("treasureChest", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "TREASURE CHEST", "tooltip-treasureChest", false);
	addItemBox("goldKey", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "GOLD KEY", "tooltip-treasureChestKey", false);
	addItemBox("sapphireGoldKey", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "SAPPHIRE KEY", "tooltip-treasureChestKey", false);
	addItemBox("emeraldGoldKey", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "EMERALD KEY", "tooltip-treasureChestKey", false);
	addItemBox("rubyGoldKey", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "RUBY KEY", "tooltip-treasureChestKey", false);
	addItemBox("diamondGoldKey", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "DIAMOND KEY", "tooltip-treasureChestKey", false);
	addItemBox("blueFurnaceOrb", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "ORB", "tooltip-orb", false);
	addItemBox("blueWoodcuttingOrb", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "ORB", "tooltip-orb", false);
	addItemBox("blueOreOrb", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "ORB", "tooltip-orb", false);
	addItemBox("blueManaOrb", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "ORB", "tooltip-orb", false);
	addItemBox("blueOilWellOrb", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "ORB", "tooltip-orb", false);
	addItemBox("shootingStar", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "SHOOTING STAR", "tooltip-shootingStar", false);
	addItemBox("telescopeLens", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "TELESCOPE LENS", "tooltip-telescopeLens", false);
	addItemBox("telescopePart", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "TELESCOPE", "tooltip-telescopeLens", false);
	addItemBox("telescope", 1, "", "item-section-home-1", "#1a344c", "#0d1a26", "TELESCOPE", "tooltip-telescopeLens", false);
	addItemBox("carePackage2", 0, "", "item-section-home-1", "#1a344c", "0d1a26", "CARE PACKAGE", "tooltip-carePackage", false);
	addItemBox("carePackage3", 0, "", "item-section-home-1", "#1a344c", "0d1a26", "CARE PACKAGE", "tooltip-carePackage", false);
	addItemBox("stardustBox1", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "STARDUST BOX I", "tooltip-stardustBox", false);
	addItemBox("stardustBox2", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "STARDUST BOX I", "tooltip-stardustBox", false);
	addItemBox("puzzleChest1", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "PUZZLE CHEST", "tooltip-puzzleChest1", false);
	addItemBox("snowmanCrafted", 0, "", "item-section-home-1", "#1a344c", "#0d1a26", "SNOWMAN", "tooltip-snowmanCrafted", false);
	addItemBox("bronzeOven", 0, "", "item-section-cooking-1", "#666600", "#333300", "BRONZE OVEN", "tooltip-oven", false);
	addItemBox("ironOven", 0, "", "item-section-cooking-1", "#666600", "#333300", "IRON OVEN", "tooltip-oven", false);
	addItemBox("silverOven", 0, "", "item-section-cooking-1", "#666600", "#333300", "SILVER OVEN", "tooltip-oven", false);
	addItemBox("goldOven", 0, "", "item-section-cooking-1", "#666600", "#333300", "GOLD OVEN", "tooltip-oven", false);
	addItemBox("promethiumOven", 0, "", "item-section-cooking-1", "#666600", "#333300", "PROM OVEN", "tooltip-oven", false);
	addItemBox("chef", 0, "", "item-section-cooking-1", "#666600", "#333300", "CHEF", "tooltip-chef", false);
	addItemBox("cooksBook1", 1, "", "item-section-cooking-1", "#666600", "#333300", "COOKS BOOK", "tooltip-cooksBook", false);
	addItemBox("cheeseStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("lavaStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("oysterStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("iceBonesStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("fishStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("honeyStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("bananaStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("appleStew", 0, "", "item-section-cooking-1", "#666600", "#333300", "STEW", "", false);
	addItemBox("yellowSpices", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SPICES", "", false);
	addItemBox("greenSpices", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SPICES", "", false);
	addItemBox("blueSpices", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SPICES", "", false);
	addItemBox("redSpices", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SPICES", "", false);
	if (getItem("cookingUnlocked") == 1)
	{
		addItemBox("apple", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "APPLE", "tooltip-apple", false);
		addItemBox("bananas", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "BANANAS", "tooltip-bananas", false);
		addItemBox("storeBananas", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "BANANAS", "tooltip-storeBananas", false);
		addItemBox("carrot", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "CARROTS", "tooltip-carrot", false);
		addItemBox("salad", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "MUSHROOM SALAD", "tooltip-salad", false);
		addItemBox("rawChicken", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "RAW CHICKEN", "tooltip-rawChicken", false);
		addItemBox("oysterMornay", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "OYSTER MORNAY", "tooltip-oysterMornay", false);
		addItemBox("rawGiantSnakeTail", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SNAKE TAIL", "tooltip-giantSnakeTail", false);
		addItemBox("giantSnakeTail", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SNAKE TAIL", "tooltip-giantSnakeTail", false);
		addItemBox("cheese", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "CHEESE", "tooltip-cheese", false);
		addItemBox("honey", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "HONEY", "tooltip-honey", false);
		addItemBox("snakeSushiShrimp", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SNAKESKIN SUSHI", "tooltip-snakeSushiShrimp", false);
		addItemBox("snakeSushiTrout", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SNAKESKIN SUSHI", "tooltip-snakeSushiShrimpTrout", false);
		addItemBox("snakeSushiTuna", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SNAKESKIN SUSHI", "tooltip-snakeSushiShrimpTuna", false);
		addItemBox("seaweedChicken", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "SEAWEED CHICKEN", "tooltip-seaweedChicken", false);
		addItemBox("batSkinSushi", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "BATSKIN SUSHI", "tooltip-batSkinSushi", false);
		addItemBox("mapleSyrup", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "MAPLE SYRUP", "tooltip-mapleSyrup", false)
	};
	addItemBox("chicken", 0, "", "item-section-cooking-1", _0x5C17, _0x5BDD, "CHICKEN", "tooltip-chicken", false)
}